name: si
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - openpyxl
  - geopandas
  - matplotlib
  - seaborn
  - plotly
  - ipykernel
  - ipython
  - folium
  - networkx
  - statsmodels
  - python-dotenv
  - pip
  - pip:
    - kagglehub
    - geodatasets
